#include "Texture.h"

void CTexture::CreateNonMipMappedTextureFromFile(const string& TextureFileName)
{
	m_TextureFileName = TextureFileName;

	size_t found{ m_TextureFileName.find_last_of(L'.') };
	string Ext{ m_TextureFileName.substr(found) };
	wstring wFileName{ m_TextureFileName.begin(), m_TextureFileName.end() };
	for (auto& c : Ext)
	{
		c = toupper(c);
	}
	if (Ext == ".DDS")
	{
		assert(SUCCEEDED(CreateDDSTextureFromFile(m_PtrDevice, wFileName.c_str(),
			(ID3D11Resource**)m_Texture2D.GetAddressOf(), &m_ShaderResourceView)));
	}
	else
	{
		assert(SUCCEEDED(CreateWICTextureFromFile(m_PtrDevice, wFileName.c_str(),
			(ID3D11Resource**)m_Texture2D.GetAddressOf(), &m_ShaderResourceView)));
	}

	SetTextureSize();
}

void CTexture::CreateAutoGeneratedMipMappedTextureFromFile(const string& TextureFileName)
{
	m_TextureFileName = TextureFileName;

	wstring wFileName{ m_TextureFileName.begin(), m_TextureFileName.end() };
	ComPtr<ID3D11Texture2D> NonMipMappedTexture{};
	CreateWICTextureFromFile(m_PtrDevice, wFileName.c_str(), (ID3D11Resource**)NonMipMappedTexture.GetAddressOf(), nullptr);

	D3D11_TEXTURE2D_DESC Texture2DDesc{};
	NonMipMappedTexture->GetDesc(&Texture2DDesc);
	Texture2DDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE | D3D11_BIND_RENDER_TARGET;
	Texture2DDesc.CPUAccessFlags = 0;
	Texture2DDesc.MipLevels = 0;
	Texture2DDesc.MiscFlags = D3D11_RESOURCE_MISC_GENERATE_MIPS;
	Texture2DDesc.Usage = D3D11_USAGE_DEFAULT;

	assert(SUCCEEDED(m_PtrDevice->CreateTexture2D(&Texture2DDesc, nullptr, m_Texture2D.GetAddressOf())));

	m_PtrDeviceContext->ResolveSubresource(m_Texture2D.Get(), 0, NonMipMappedTexture.Get(), 0, Texture2DDesc.Format);

	m_PtrDevice->CreateShaderResourceView(m_Texture2D.Get(), nullptr, m_ShaderResourceView.GetAddressOf());

	m_PtrDeviceContext->GenerateMips(m_ShaderResourceView.Get());

	SetTextureSize();
}

void CTexture::CreateWICFromMemory(const vector<uint8_t>& RawData)
{
	assert(SUCCEEDED(CreateWICTextureFromMemory(m_PtrDevice, &RawData[0], RawData.size(), 
		(ID3D11Resource**)m_Texture2D.GetAddressOf(), &m_ShaderResourceView)));

	SetTextureSize();
}

void CTexture::CreateBlankTexture(DXGI_FORMAT Format, const XMFLOAT2& TextureSize)
{
	m_TextureSize = TextureSize;

	D3D11_TEXTURE2D_DESC Texture2DDesc{};
	Texture2DDesc.ArraySize = 1;
	Texture2DDesc.BindFlags = D3D11_BIND_SHADER_RESOURCE;
	Texture2DDesc.CPUAccessFlags = D3D11_CPU_ACCESS_WRITE;
	Texture2DDesc.Format = Format;
	Texture2DDesc.Height = static_cast<UINT>(m_TextureSize.y);
	Texture2DDesc.MipLevels = 1;
	Texture2DDesc.SampleDesc.Count = 1;
	Texture2DDesc.SampleDesc.Quality = 0;
	Texture2DDesc.Usage = D3D11_USAGE_DYNAMIC;
	Texture2DDesc.Width = static_cast<UINT>(m_TextureSize.x);

	m_PtrDevice->CreateTexture2D(&Texture2DDesc, nullptr, m_Texture2D.GetAddressOf());
	m_PtrDevice->CreateShaderResourceView(m_Texture2D.Get(), nullptr, m_ShaderResourceView.GetAddressOf());
}

void CTexture::SetTextureSize()
{
	D3D11_TEXTURE2D_DESC Texture2DDesc{};
	m_Texture2D->GetDesc(&Texture2DDesc);

	m_TextureSize.x = static_cast<float>(Texture2DDesc.Width);
	m_TextureSize.x = static_cast<float>(Texture2DDesc.Height);
}

void CTexture::UpdateTextureRawData(const SPixelUNorm* PtrData)
{
	D3D11_MAPPED_SUBRESOURCE MappedSubresource{};
	if (SUCCEEDED(m_PtrDeviceContext->Map(m_Texture2D.Get(), 0, D3D11_MAP_WRITE_DISCARD, 0, &MappedSubresource)))
	{
		size_t SrcRowPixelCount{ (size_t)m_TextureSize.x };
		uint8_t* PtrDest{ (uint8_t*)MappedSubresource.pData };

		UINT RowCount{ MappedSubresource.DepthPitch / MappedSubresource.RowPitch };
		for (UINT iRow = 0; iRow < RowCount; ++iRow)
		{
			memcpy(PtrDest + (iRow * MappedSubresource.RowPitch), PtrData + (iRow * SrcRowPixelCount), SrcRowPixelCount * sizeof(SPixelUNorm));
		}

		m_PtrDeviceContext->Unmap(m_Texture2D.Get(), 0);
	}
}

void CTexture::SetSlot(UINT Slot)
{
	m_Slot = Slot;
}

void CTexture::Use(int ForcedSlot) const
{
	if (ForcedSlot != -1)
	{
		m_PtrDeviceContext->PSSetShaderResources(static_cast<UINT>(ForcedSlot), 1, m_ShaderResourceView.GetAddressOf());
	}
	else
	{
		m_PtrDeviceContext->PSSetShaderResources(m_Slot, 1, m_ShaderResourceView.GetAddressOf());
	}
}